
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-saroka-click-tls
  namespace: argocd
spec:
  secretName: argo-saroka-click-tls
  duration: 2160h #90day
  renewBefore: 360h #before 15day
  issuerRef:
    name: my-issuer
    kind: ClusterIssuer
  commonName: argo.saroka.click
  dnsNames:
  - argo.saroka.click